language: python
python:
  - "2.7"

before_install:
  - wget https://repo.anaconda.com/archive/Anaconda2-5.3.1-Linux-x86_64.sh -O conda.sh
  - chmod a+x conda.sh
  - travis_wait ./conda.sh -b
  - export PATH=/home/travis/anaconda2/bin:$PATH
  - travis_wait conda update --yes conda

install:
  - conda create --yes -n hc27 python=$TRAVIS_PYTHON_VERSION
  - source activate hc27
  - pip install -r requirements.txt

script:
  - cd examples && ./start_example.sh
